baseURL = 'https:0.0.0.0:1313/'
languageCode = 'en-us'
title = 'Second-Brain'
theme = "hermit-v2"

enableGitInfo = true

pygmentsCodefences  = true
pygmentsUseClasses  = true

copyright = "Everything you say can and will be used aganst you."

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]
tocc = true
ShowLastmod = true

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10
