baseURL = 'https://demetrebadzaradze.github.io/Second-Brain/'
languageCode = 'en-us'
title = 'Second-Brain'
theme = "hermit-V2"

enableGitInfo = true

pygmentsCodefences  = true
pygmentsUseClasses  = true

copyright = "The actual content on this site other then code is under CC BY-NC 4.0 licence"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]
tocc = true
ShowLastmod = true

[params.author]
    name = "Demetre Badzgaradze"
    about = "#IDONTKNOW"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  description = "this is my second brain"
  # images = [""]
  themeColor = "#494f5c"

  homeSubtitle = "Brain is not for containing ideas, But coming up with them. That's why I got second one."
  footerCopyright = "The actual content on this site other then code is under CC BY-NC 4.0 licence"
  footerHideThemeName = true
  # bgImg = ""
  gitUrl = "https://github.com/demetrebadzaradze"

  justifyContent = false

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true 
  global_mathjax = false
  readTime = true
  readTimeSeparator = "words, "
  # legacyLayout = false
  shareSocial = true
  # googleTagManager = "GTM-XXXXXXXX"
  # tagSymbol = "#"
  # categorySymbol = "⊲"
  # pinned = "Pinned Posts"
  # pinnedSVGname = "pin"
  # descriptionInPosts= true
  # initialPublish = "Initally Posted on: "
  # human = ["single","posts"]
  # noIndex = false
  # denyRobots = "noindex, nofollow, noarchive"
  allowRobots = "index, follow"
  # siteNoIndex = false
  # noIndexPages = ["404 Page not found"]
  # usesAnimation = true

  [[params.socialLinks]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/demetre-badzgaradze-b49153291/"

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/demetrebadzaradze"
  [[params.toc]]
    toc = true


[menu]
  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20
